version: 2.1
executors:
  helm: 
    docker:
      - image: alpine/helm
parameters:
  subPath:
    type: string
    default: ""
  

commands:
   repo_add:
     description: "Adding helm repo"
     steps: 
       - run: |     
       
           helm plugin install https://github.com/hayorov/helm-gcs.git
           helm plugin update gcs
           helm gcs init gs://bucket/path
           helm repo add myrepo gs://bucket/path
   package:
     description: "getting chart name from tag"
     steps: 
       - run: |    
           helm dependency update
           helm package $workDir
           helm push 
jobs:
  build:
    executor: helm
    environment:  
      workDir: << pipeline.parameters.subPath >>
    steps:
     - checkout 
     - repo_add
     - package

workflows:
  version: 2
  service_A:
    when:
      condition:
        equal: [ "service-A", "service-B",   << pipeline.paramaters.job_env >> ]
    jobs:
      - build:
          name:  'pushing chart of service_A'

  

  