version: 2.1
executors:
  helm: 
    docker:
      - image: alpine/helm
parameters:
  subpath:
    type: string
    default: ""

commands:
   repo_add:
     description: "Adding helm repo"
     steps: 
       - run: |     
          
           helm plugin install https://github.com/hayorov/helm-gcs.git
           helm plugin update gcs
          
   package:
     description: "getting chart name from tag"
     steps: 
       - run: |    
           helm dependency update
           ls -la 
           helm package << pipeline.parameters.subpath >> 
      
jobs:
  build:
    executor: helm 
    working_directory: <<pipeline.parameters.subpath>>
    steps:
     - checkout 
     - repo_add
     - package

workflows:
  version: 2
  service_A:
    when:   
      and:
       - equal: [ service-A, << pipeline.parameters.subpath >>  ]
    jobs:
      - build:
          name:  'pushing chart of service_A'
  service_B:
    when:
      and:
       - equal: [ service-B, << pipeline.parameters.subpath >>  ]
    jobs:
      - build:
          name:  'pushing chart of service_B'        

  
