version: 2.1
executors:
  helm: 
    docker:
      - image: alpine/helm
parameters:
  service-A:
    type: boolean
    default: false
  service-B:
    type: boolean
    default: false

commands:
   repo_add:
     description: "Adding helm repo"
     steps: 
       - run: |       
           helm repo add myrepo https://devopsrajpurohit.github.io/helm/
   package:
     description: "getting chart name from tag"
     steps: 
       - run: |    
           cd  << parameters.dirPath >> 
           helm package  .  --version $CIRCLE_BUILD_NUM 
jobs:
  build:
    executor: helm
    parameters:
      dirPath:
        description: base path for service 
        type: string
        default: "service-A"
     
    steps:
     - checkout 
     - repo_add
     - package

workflows:
  version: 2
  service_A:
    when:
      or:
        - << pipeline.parameters.service-A >>
    jobs:
      - build:
         name:  'pushing chart of service_A'
         dirPath: "service-A"

  service_B:
    when:
      or:
        - << pipeline.parameters.service-B >>
    jobs:
      - build:
          name:  'pushing chart of service_A'
          dirPath: "service-B"

  