version: 2.1
executors:
  helm: 
    docker:
      - image: alpine/helm
parameters:
  service-A:
    type: boolean
    default: false
  service-B:
    type: boolean
    default: false

commands:
   repo_add:
     description: "Adding helm repo"
     steps: 
       - run: |       
           helm repo add myrepo https://devopsrajpurohit.github.io/helm/
   package:
     description: "getting chart name from tag"
     steps: 
       - run: |    
           helm package $workDir
jobs:
  build:
    executor: helm
    parameters: 
      subPath:  
        description: path 
        type: string 
        default: ""
    environment:  
      workDir: << parameters.subPath >>
    steps:
     - checkout 
     - repo_add
     - package

workflows:
  version: 2
  service_A:
    when:
      or:
        - << pipeline.parameters.service-A >>
    jobs:
      - build:
          name:  'pushing chart of service_A'
          subPath: service-A

  service_B:
    when:
      or:
        - << pipeline.parameters.service-B >>
    jobs:
      - build:
          name:  'pushing chart of service_A'
          subPath: service-B
          
          

  