version: 2.1
executors:
  helm: 
    docker:
      - image: alpine/helm
parameters:
  service_A:
    type: boolean
    default: false
  service_B:
    type: boolean
    default: false

commands:
   repo_add:
     description: "Adding helm repo"
     steps: 
       - run: |       
           helm repo add myrepo https://devopsrajpurohit.github.io/helm/
   package:
     description: "getting chart name from tag"
     steps: 
       - run: |       
           helm package  . --version $CIRCLE_BUILD_NUM 
jobs:
  build:
    executor: helm
    steps:
     - checkout 
     - repo_add
     - package

workflows:
  service_A:
    when:
      or:
        - << pipeline.parameters.service_A >>
    jobs:
      - build
          filters:
            branches:
              only: master
  service_B:
    when:
      or:
        - << pipeline.parameters.service_B >>
    jobs:
      - build
          filters:
            branches:
              only: master